### ISSUE TITLE
Rename to geojson-simplify?

### ISSUE THREAD

**Issue by freenerd** [mapbox/geojson-tidy#10]
I think `simplify` is more descriptive of what we are doing. `tidy` sounds like cleaning up, but it's not clear what that really means.

**Comment by morganherlocker** [comment]
"Simplify" is pretty overloaded in the space. I think many would think this must be Douglas-Peucker algorithm variant like [simplify-js](https://github.com/mourner/simplify-js/). This particular algorithm is probably closer to something like a [lowpass filter](https://en.wikipedia.org/wiki/Low-pass_filter).

**Comment by tmcw** [comment]
I agree with @morganherlocker - this isn't simplification in the common sense of the term.
