### ISSUE TITLE
don't strip out custom properties, filter them as a option

### ISSUE THREAD

**Issue by cordovapolymer** [mapbox/geojson-tidy#12]
It would be great if geojson-tidy had an option to keep properties and accept a array of properties to filter together with coordinates. 

Also it would be nice that it would follow naming from [W3C specs](https://dev.w3.org/geo/api/spec-source.html):

```
geometry.coordinates;
properties.timestamps;
properties.headings;
properties.accuracies;
```

**Comment by tmcw** [comment]
Closing in favor of #6 and reiterating that W3C specs do not apply to GeoJSON.
