### ISSUE TITLE
Allow Unix timestamps and ISO 8601

### ISSUE THREAD

**Issue by freenerd** [mapbox/geojson-tidy#2]
For map matching we accept both kinds:

> Timestamps are located in the `coordTimes` array. The timestamps may either be numbers in [Unix time](https://en.wikipedia.org/wiki/Unix_time) or Strings in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.

Do we want to do the same thing here? And/or what's the most common date formats in geojson?

**Comment by planemad** [comment]
@freenerd  The timestamps are processed using the [javascript Date()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) method, so both formats are supported including some more common ones.
