### ISSUE TITLE
Return object?

### ISSUE THREAD

**Issue by freenerd** [mapbox/geojson-tidy#7]
Currently the tidy function [returns a string](https://github.com/mapbox/geojson-tidy/blob/f7d37a77af25b32b28b546e985ad9792092a4dca/geojson-tidy.js#L122). Why not return an object? My feeling is that users would want to continue manipulating the object, thus they'd need to immediatly `JSON.parse` again.

**Comment by planemad** [comment]
@freenerd it was to make it easy to run it from terminal and write to an output file. Guess i'll make it return a string from CLI and object otherwise? @aaronlidman

**Comment by freenerd** [comment]
sounds good
